apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrhyv2-flask-deploy
  labels:
    service: hrhyv2-flask
spec:
  replicas: 3
  selector:
    matchLabels:
      service: hrhyv2-flask
  template:
    metadata:
      labels:
        service: hrhyv2-flask
    spec:
      containers:
      - name: hrhyv2-flask
        image: 812675885124.dkr.ecr.ap-northeast-1.amazonaws.com/myrepo:latest 
        env:
        - name: FLASK_DB_URL
          valueFrom:
            secretKeyRef:
              name: hrhyv2-flask-secret
              key: FLASK_DB_URL
        - name: FLASK_DB_NAME
          valueFrom:
            secretKeyRef:
              name: hrhyv2-flask-secret
              key: FLASK_DB_NAME
        - name: FLASK_DB_USER
          valueFrom:
            secretKeyRef:
              name: hrhyv2-flask-secret
              key: FLASK_DB_USER
        - name: FLASK_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hrhyv2-flask-secret
              key: FLASK_DB_PASSWORD
        - name: FLASK_APP
          valueFrom:
            secretKeyRef:
              name: hrhyv2-flask-secret
              key: FLASK_APP
        ports:
        - containerPort: 5000
