apiVersion: v1
kind: Service
metadata:
  labels:
    service: hrhyv2-flask
  name: hrhyv2-flask-svc
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  type: LoadBalancer
  selector:
    service: hrhyv2-flask